version: "3"
services:
  node1:
    build: .
    container_name: node1
    ports:
      - "8081:80"   # Web
      - "2221:22"   # SSH
  node2:
    build: .
    container_name: node2
    ports:
      - "8082:80"
      - "2222:22"
  node3:
    build: .
    container_name: node3
    ports:
      - "8083:80"
      - "2223:22"
  node4:
    build: .
    container_name: node4
    ports:
      - "8084:80"
      - "2224:22"
  node5:
    build: .
    container_name: node5
    ports:
      - "8085:80"
      - "2225:22"

